### PR TITLE
fail grunt build task on error lint

### PR DESCRIPTION
**Pull request by fernandoPalaciosGit**
I want to propose a solution to issue #8 , on multitask or synchronous tasks grunt does not stop execution. Thank you.

### CODE REVIEW

**Comment by builtbyjay** [comment]
This seems to do exactly what it's supposed to. My build task now fails if there is a linting warning/error. Thank you @fernandoPalaciosGit!

**Comment by tomhardman0** [comment]
Please merge this :+1:

**Comment by DanPurdy** [comment]
@micahgodbolt this looks good to me if you want to pump a new release out.

**Comment by micahgodbolt** [comment]
taking a look

**Comment by ajwagner777** [comment]
Maybe I am missing something, but warnings fail the build, when only errors should.  I've only been using this for a couple of days now; was this the case before this merge?

**Pull request merged**
