### PR TITLE
Update sass-lint package to 1.9.1; js code format

### PR DESCRIPTION
**Pull request by mateuszkosmider**
Hi, I noticed that sass-lint dependency is out of date so I update this to 1.9.1. Also I format some js code to look better (mostly unreadable indentation).

### CODE REVIEW

**Comment by DanPurdy** [comment]
@mateuszkosmider by specifying the version with a leading `^` it was basically saying install the latest version of 1.x.x you can find. So if you install this now as it is without your PR you'd still get `v1.9.1` installed with it.

**Comment by mateuszkosmider** [comment]
It should :) but when I install this package, sass-lint version that I get is 1.8.2, and I don't know why.

**Comment by DanPurdy** [comment]
Have you cleared all the projects node modules and installed again might be a version hanging around? @micahgodbolt would you be able to pop this out as a release?

**Comment by mateuszkosmider** [comment]
You are right, there was something with cache in my app. When I create separate folder and here install  this package the sass-lint was installed in 1.9.1 so it works as expected. Thanks a lot :)

**Comment by DanPurdy** [comment]
Will close this but pin releases in future I think.

**Pull request closed without merging**
