### PR TITLE
Update to #15 - Dgerike master

### PR DESCRIPTION
**Pull request by micahgodbolt**
Changed grunt param to outputFile for consistency, and aliased value when passed in opts.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Updated to #15

**Comment by dgerike** [comment]
Looking good! Everything still working as expected. Thanks!

**Comment by aberonni** [comment]
Hi, can i +1 this pull request? It seems that outputFile isn't working for me at the moment, and the changes committed to tasks/sass-lint.js seem to do the trick.

Thx

**Comment by micahgodbolt** [comment]
Great! That's 2 thumbs up.

**Pull request merged**
