### PR TITLE
Adds configFile option to change the location of the .yml

### PR DESCRIPTION
**Pull request by whazap**
* Requires newer sass-lint version, 1.2.0

### CODE REVIEW

**Comment by davetgreen** [comment]
I can't wait for this, it's the only thing preventing me from dumping grunt-scss-lint! :+1:

**Comment by bgriffith** [comment]
Looks good

**Comment by micahgodbolt** [comment]
Thanks!

**Comment by davetgreen** [comment]
Thanks @whazap for the PR and @micahgodbolt for merging. I'm going to test this in my local dev set-up right now! :+1:

**Pull request merged**
