### PR TITLE
Changed logic slightly so that warnings would allow grunt task to pass

### PR DESCRIPTION
**Pull request by ajwagner777**
Warnings were failing the grunt task.  Would prefer to allow warnings, and fail on errors.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Please resolve conflicts from the latest release and push again. Thanks for the submission!

**Comment by ajwagner777** [comment]
Conflicts resolved

**Comment by micahgodbolt** [comment]
Thanks! I'll take a look.

**Comment by steveworkman** [comment]
I've got an alternative to this in https://github.com/sasstools/grunt-sass-lint/pull/19 which allows you to specify this as an optional parameter. This has the added benefit of not changing anyone else's configuration by default should they upgrade, and also has some documentation with it.

**Comment by DanPurdy** [comment]
@steveworkman this is a bug though in my opinion. It's originated from a change in sass-lint as we (I :disappointed:) refactored how the errors and warnings were counted, this possibly had side effects here. Warnings should never fail a build by design unless an option was added to allow this which i don't know why we would as thats what errors or status '2' are for. The 'quiet' option (we use the -q flag) in sass-lint prevents errors from failing your build so i'm not sure it should be added as a option with different functionality to this plugin.

So i would say #18 actually suits the problem better than #19. What do you think @micahgodbolt ?

**Comment by micahgodbolt** [comment]
@DanPurdy I'd certainly want to emulate the functionality of sass-lint as closely as possible. I would expect a config file from a gulp project to have the same effect in a grunt project.

**Comment by DanPurdy** [comment]
Definitely there isn't any change to a config file happening here it's just a functionality/implementation question. #19 is proposing that warnings should still in certain cases be able to fail a build which going by sass-lint's logic isn't possible and I would say currently is a bug. 

Warnings imo should be mutable or just displayed to the user without ever throwing and errors should either fail a build on the first error encountered or give users a list of all the errors found without throwing.

So it's just down to whether you want warnings to be able to fail builds or not going forward. :smile:

**Comment by ajwagner777** [comment]
IMO as well, warning are just that, "hey look at me, you should probably fix me because you said I was semi important in the config file"

Anything that is super important can be set to throw an error and stop the build.

**Comment by steveworkman** [comment]
@DanPurdy I'm happy to abandon #19 in favour of #18

**Comment by steveworkman** [comment]
@micahgodbolt @DanPurdy any updates on this?

**Comment by micahgodbolt** [comment]
I'll give it a last look today and merge it in. Just wanted to give people
a chance to weigh in

**Comment by micahgodbolt** [comment]
Sorry for the delay. Looks good! now 0 is don't test, 1 is warn, and 2 will fail

**Pull request merged**
