### PR TITLE
Update Sass-lint version

### PR DESCRIPTION
**Pull request by ifyoumakeit**
Bump Sass-lint version from 1.2 to 1.3.

[Changelog](https://github.com/sasstools/sass-lint/blob/develop/CHANGELOG.md)

### CODE REVIEW

**Comment by DanPurdy** [comment]
I would hold off for a moment, I'm going to push 1.4.0 out today hopefully..

**Comment by ifyoumakeit** [comment]
Oh nice. Looking forward to `class-name-format`.

**Comment by DanPurdy** [comment]
Also the dependencies are set at '^1.2.0` so this wont actually be necessary as this will automatically oull down a version of `sass-lint` < `2.0.0` you'd just need to remove your current copy of this and re download.

**Comment by ifyoumakeit** [comment]
Ah good point. I mixed up `~` and `^`.

**Comment by DanPurdy** [comment]
Ha, no worries, I had to double check too :flushed:

**Pull request closed without merging**
